import { Questionnaire } from "@/types";

export const scl90: Questionnaire = {
    id: "scl90",
    title: "SCL-90 Simptomlar Siyahısı",
    description: "Psixi sağlamlığın və psixopatoloji simptomların hərtərəfli qiymətləndirilməsi",
    tags: ["Özünüqiymətləndirmə", "Psixi Sağlamlıq", "Skrininq"],
    time: "10-15 dəqiqə",
    details: {
        introduction: "Simptomlar Siyahısı-90 (SCL-90) dünyada ən geniş istifadə olunan psixoloji skrininq vasitələrindən biridir. Geniş spektrli psixoloji problemləri və psixopatoloji simptomları qiymətləndirmək üçün hazırlanıb. SCL-90 hisslər, emosiyalar, düşüncə, şüur, davranışdan tutmuş həyat tərzi, şəxslərarası münasibətlər, qidalanma və yuxu vərdişlərinə qədər geniş sahələri əhatə edən 90 bənddən ibarətdir.",
        questionCount: "90 sual",
        evaluationTime: "Adətən 10-15 dəqiqə",
        instructions: "Zəhmət olmasa hər bəndi diqqətlə oxuyun və real vəziyyətinizə əsaslanaraq həmin problemin son həftə ərzində sizi nə dərəcədə narahat etdiyini qiymətləndirin. Təcrübənizi ən yaxşı təsvir edən variantı seçin.",
        scoringMethod: [
            "Ümumi bal: bütün bəndlərin balının cəmi",
            "Pozitiv bəndlər: ≥2 bal alan bəndlərin sayı",
            "Pozitiv simptom ortalaması: ümumi pozitiv bal / pozitiv bəndlərin sayı",
            "Şiddət: ümumi bal >160 və ya pozitiv bənd sayı >43 psixoloji problemlərə işarə edir"
        ],
        dimensions: [
            { name: "Somatizasiya", description: "Ürək-damar, mədə-bağırsaq, tənəffüs simptomları daxil olmaqla fiziki narahatlıq" },
            { name: "Obsessiv-Kompulsiv", description: "Obsessiv fikirlər və kompulsiv davranışlar" },
            { name: "Şəxslərarası Həssaslıq", description: "Şəxslərarası qarşılıqlı əlaqədə yetərsizlik və aşağılıq hissləri" },
            { name: "Depressiya", description: "Depressiv əhval, maraq itkisi, ümidsizlik hissləri" },
            { name: "Narahatlıq", description: "Gərginlik, əsəbilik, qorxu və əlaqədar emosional təcrübələr" },
            { name: "Düşmənçilik", description: "Qəzəb, aqressivlik, əsəbilik və əlaqədar emosiyalar" },
            { name: "Fobik Narahatlıq", description: "Müəyyən yerlərdən, insanlardan və ya vəziyyətlərdən qorxu" },
            { name: "Paranoid Fikirlər", description: "Proyektiv düşüncə, şübhəçilik, düşmənçilik" },
            { name: "Psixotisizm", description: "Hallüsinasiyalar, sanrılar, düşüncə pozuntuları" },
            { name: "Əlavə Bəndlər", description: "Yuxu, qidalanma və cinsi problemlər" }
        ],
        notes: [
            "Qiymətləndirmə sakit, narahat edilməyəcəyiniz mühitdə aparılmalıdır",
            "Həqiqi hisslərinizi əks etdirmək üçün həddindən artıq düşünmədən səmimi cavab verin",
            "Ballar yüksəkdirsə, psixi sağlamlıq mütəxəssisi ilə məsləhətləşməyi düşünün"
        ],
        references: [
            {
                text: "Derogatis, L. R. (1977). SCL-90: Administration, scoring and procedure manual for the revised version. Clinical Psychometric Research.",
                url: "https://www.pearsonassessments.com"
            }
        ]
    },
    questions: [
        { id: 1, content: "Baş ağrıları" },
        { id: 2, content: "Daxildə əsəbilik və ya titrəmə hissi" },
        { id: 3, content: "Ağlınızdan getməyən təkrarlanan xoşagəlməz fikirlər" },
        { id: 4, content: "Zəiflik hissi və ya başgicəllənmə" },
        { id: 5, content: "Cinsi maraq və ya həzzin itməsi" },
        { id: 6, content: "Başqalarını tənqid etmə hissi" },
        { id: 7, content: "Kiminsə sizin fikirlərinizi idarə edə biləcəyi fikri" },
        { id: 8, content: "Problemlərinizin əksəriyyətində başqalarının günahkar olduğunu hiss etmək" },
        { id: 9, content: "Xatırlamaqda çətinlik" },
        { id: 10, content: "Səliqəsizlik və ya diqqətsizlik barədə narahatlıq" },
        { id: 11, content: "Asanlıqla qıcıqlanmaq və ya əsəbiləşmək" },
        { id: 12, content: "Ürəkdə və ya sinədə ağrılar" },
        { id: 13, content: "Açıq məkanlarda və ya küçələrdə qorxu hissi" },
        { id: 14, content: "Enerji azlığı və ya yavaşımış hiss" },
        { id: 15, content: "Həyatınıza son qoymaq haqqında fikirlər" },
        { id: 16, content: "Başqalarının eşitmədiyi səsləri eşitmək" },
        { id: 17, content: "Titrəmə" },
        { id: 18, content: "Əksər insanlara etibar edilə bilməyəcəyi hissi" },
        { id: 19, content: "Zəif iştah" },
        { id: 20, content: "Asanlıqla ağlamaq" },
        { id: 21, content: "Əks cinslə utancaqlıq və ya narahatlıq hiss etmək" },
        { id: 22, content: "Tələyə düşmüş və ya ilişib qalmış hiss" },
        { id: 23, content: "Səbəbsiz yerə qəflətən qorxuya düşmək" },
        { id: 24, content: "Nəzarət edə bilmədiyiniz qəzəb partlayışları" },
        { id: 25, content: "Evdən tək çıxmaqdan qorxmaq" },
        { id: 26, content: "Hər şeydə özünü günahlandırmaq" },
        { id: 27, content: "Bel nahiyəsində ağrılar" },
        { id: 28, content: "İşləri görməkdə blok olma hissi" },
        { id: 29, content: "Tənhalıq hissi" },
        { id: 30, content: "Kədərli hiss etmək" },
        { id: 31, content: "Şeylər barədə həddindən artıq narahat olmaq" },
        { id: 32, content: "Heç bir şeyə maraq göstərməmək" },
        { id: 33, content: "Qorxu hiss etmək" },
        { id: 34, content: "Hisslərinizin asanlıqla incimsi" },
        { id: 35, content: "Başqalarının sizin şəxsi fikirlərinizdən xəbərdar olması" },
        { id: 36, content: "Başqalarının sizi anlamadığını və ya sizə şəfqət göstərmədiyini hiss etmək" },
        { id: 37, content: "İnsanların dostyana olmadığını və ya sizi sevmədiyini hiss etmək" },
        { id: 38, content: "Düzgünlüyü təmin etmək üçün işləri çox yavaş görmək məcburiyyəti" },
        { id: 39, content: "Ürəyin döyünməsi və ya sürətlə vurması" },
        { id: 40, content: "Ürəkbulanma və ya mədə narahatlığı" },
        { id: 41, content: "Başqalarından aşağı olduğunuzu hiss etmək" },
        { id: 42, content: "Əzələ ağrıları" },
        { id: 43, content: "Başqalarının sizi izlədiyini və ya haqqınızda danışdığını hiss etmək" },
        { id: 44, content: "Yuxuya getməkdə çətinlik" },
        { id: 45, content: "Etdiyiniz işi yenidən və yenidən yoxlamaq məcburiyyəti" },
        { id: 46, content: "Qərar verməkdə çətinlik" },
        { id: 47, content: "Avtobus, metro və ya qatarla səyahət etməkdən qorxmaq" },
        { id: 48, content: "Nəfəs almaqda çətinlik" },
        { id: 49, content: "İsti və ya soyuq keçirmə halları" },
        { id: 50, content: "Sizi qorxutduğu üçün müəyyən şeylərdən, yerlərdən və ya fəaliyyətlərdən qaçmaq məcburiyyəti" },
        { id: 51, content: "Zehninizin boşalması" },
        { id: 52, content: "Bədəninizin müxtəlif yerlərində keyimə və ya qıcıqlanma" },
        { id: 53, content: "Boğazınızda yumaq hissi" },
        { id: 54, content: "Gələcək barədə ümidsizlik hissi" },
        { id: 55, content: "Diqqəti cəmləməkdə çətinlik" },
        { id: 56, content: "Bədəninizin müxtəlif yerlərində zəiflik hissi" },
        { id: 57, content: "Gərgin və ya sıxılmış hiss etmək" },
        { id: 58, content: "Qol və ya ayaqlarda ağırlıq hissi" },
        { id: 59, content: "Ölüm haqqında fikirlər" },
        { id: 60, content: "Həddindən artıq yemək" },
        { id: 61, content: "İnsanlar sizə baxanda və ya haqqınızda danışanda narahat hiss etmək" },
        { id: 62, content: "Sizə aid olmayan fikirlərin olması" },
        { id: 63, content: "Kiməsə vurmaq, zədə vermək və ya zərər yetirmək istəyi" },
        { id: 64, content: "Səhər erkən oyanmaq" },
        { id: 65, content: "Toxunmaq, saymaq və ya yuma kimi eyni hərəkəti təkrarlamaq məcburiyyəti" },
        { id: 66, content: "Narahat və ya pozulmuş yuxu" },
        { id: 67, content: "Bir şeyi qırmaq və ya sındırmaq istəyi" },
        { id: 68, content: "Başqalarının bölüşmədiyi fikir və ya inanclara sahib olmaq" },
        { id: 69, content: "Başqaları ilə özünü çox narahat hiss etmək" },
        { id: 70, content: "Alış-veriş və ya kino kimi izdihamlı yerlərdə narahat hiss etmək" },
        { id: 71, content: "Hər şeyin böyük səy tələb etdiyini hiss etmək" },
        { id: 72, content: "Dəhşət və ya panika halları" },
        { id: 73, content: "İctimai yerlərdə yemək və ya içməkdən narahat olmaq" },
        { id: 74, content: "Tez-tez mübahisələrə girmək" },
        { id: 75, content: "Tək qaldıqda əsəbi hiss etmək" },
        { id: 76, content: "Başqalarının nailiyyətlərinizi lazımınca qiymətləndirməməsi" },
        { id: 77, content: "İnsanların yanında olsanız belə tənha hiss etmək" },
        { id: 78, content: "Yerində dura bilməyəcək qədər narahat hiss etmək" },
        { id: 79, content: "Dəyərsizlik hissi" },
        { id: 80, content: "Tanış şeylərin qəribə və ya real olmayan görünməsi hissi" },
        { id: 81, content: "Bağırmaq və ya əşyaları atmaq" },
        { id: 82, content: "İctimai yerdə huşunuzu itirəcəyinizdən qorxmaq" },
        { id: 83, content: "İmkan versəniz insanların sizdən sui-istifadə edəcəyini hiss etmək" },
        { id: 84, content: "Sizi çox narahat edən cinsi fikirlərin olması" },
        { id: 85, content: "Günahlarınıza görə cəzalandırılmalı olduğunuz fikri" },
        { id: 86, content: "İşləri görməyə vadar edilmiş hiss" },
        { id: 87, content: "Bədəninizdə ciddi bir problem olduğu fikri" },
        { id: 88, content: "Heç vaxt başqa bir insana yaxın hiss etməmək" },
        { id: 89, content: "Təqsirkarlıq hissi" },
        { id: 90, content: "Zehninizdə bir problem olduğu fikri" }
    ],
    renderOptions: () => [
        { id: 1, content: "Heç vaxt", value: "1" },
        { id: 2, content: "Bir az", value: "2" },
        { id: 3, content: "Orta dərəcədə", value: "3" },
        { id: 4, content: "Kifayət qədər", value: "4" },
        { id: 5, content: "Həddindən artıq", value: "5" }
    ]
};
